AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{PROJECT_NAME}} - {{PROJECT_DESCRIPTION}}

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12
    Architectures:
      - x86_64
    Environment:
      Variables:
        SECRET_NAME: {{PROJECT_NAME}}/prod
        AWS_REGION_NAME: {{AWS_REGION}}
        TRACE_BUCKET: !Ref TraceBucket

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - dev
    Description: Deployment environment
  DomainName:
    Type: String
    Description: Custom domain for the app (e.g., my-app.evehwang.com)
    Default: ""
  CertificateArn:
    Type: String
    Description: ACM certificate ARN (wildcard cert in us-east-1)
    Default: "arn:aws:acm:us-east-1:070840362692:certificate/7358ccd1-846d-4b50-9ccc-b511faa8a4b1"
  HostedZoneId:
    Type: String
    Description: Route 53 hosted zone ID for evehwang.com
    Default: "Z05581993IIU4AAT9GY4N"

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, ""]]

Resources:
  # Lambda Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "{{PROJECT_NAME}}-${Environment}"
      CodeUri: backend/
      Handler: src.handler.lambda_handler
      Description: "{{PROJECT_DESCRIPTION}}"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:{{AWS_REGION}}:${AWS::AccountId}:secret:{{PROJECT_NAME}}/*"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - !GetAtt TraceBucket.Arn
                - !Sub "${TraceBucket.Arn}/*"
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: GET
            RestApiId: !Ref ApiGateway
        Root:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ApiGateway
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway

  # S3 Bucket for Traces
  TraceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "{{PROJECT_NAME}}-traces-${Environment}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldTraces
            Status: Enabled
            ExpirationInDays: 30
            Prefix: traces/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "{{PROJECT_NAME}}-api-${Environment}"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "{{PROJECT_NAME}}-frontend-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Origin Access Control for CloudFront
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "{{PROJECT_NAME}}-oac-${Environment}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Bucket Policy for CloudFront Access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Aliases: !If
          - HasCustomDomain
          - - !Ref DomainName
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100

  # Route 53 DNS Record
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasCustomDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.{{AWS_REGION}}.amazonaws.com/${Environment}/"

  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn

  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref ApiFunction

  TraceBucketName:
    Description: "S3 Bucket for Traces"
    Value: !Ref TraceBucket

  TraceBucketArn:
    Description: "S3 Bucket ARN for Traces"
    Value: !GetAtt TraceBucket.Arn

  FrontendBucketName:
    Description: "S3 Bucket for Frontend"
    Value: !Ref FrontendBucket

  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution

  CloudFrontDomainName:
    Description: "CloudFront Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName

  AppUrl:
    Description: "Application URL"
    Value: !If
      - HasCustomDomain
      - !Sub "https://${DomainName}"
      - !Sub "https://${CloudFrontDistribution.DomainName}"
